version: 2
updates:
- package-ecosystem: nuget
  directory: "/ServiceWorkflowPlugin"
  schedule:
    interval: daily
- package-ecosystem: nuget
  directory: "/ServiceWorkflowPlugin.Integration.Test"
  schedule:
    interval: daily